 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/commnents", type: :request do
  
  # Commnent. As you add validations to Commnent, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Commnent.create! valid_attributes
      get commnents_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      commnent = Commnent.create! valid_attributes
      get commnent_url(commnent)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_commnent_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      commnent = Commnent.create! valid_attributes
      get edit_commnent_url(commnent)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Commnent" do
        expect {
          post commnents_url, params: { commnent: valid_attributes }
        }.to change(Commnent, :count).by(1)
      end

      it "redirects to the created commnent" do
        post commnents_url, params: { commnent: valid_attributes }
        expect(response).to redirect_to(commnent_url(Commnent.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Commnent" do
        expect {
          post commnents_url, params: { commnent: invalid_attributes }
        }.to change(Commnent, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post commnents_url, params: { commnent: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested commnent" do
        commnent = Commnent.create! valid_attributes
        patch commnent_url(commnent), params: { commnent: new_attributes }
        commnent.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the commnent" do
        commnent = Commnent.create! valid_attributes
        patch commnent_url(commnent), params: { commnent: new_attributes }
        commnent.reload
        expect(response).to redirect_to(commnent_url(commnent))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        commnent = Commnent.create! valid_attributes
        patch commnent_url(commnent), params: { commnent: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested commnent" do
      commnent = Commnent.create! valid_attributes
      expect {
        delete commnent_url(commnent)
      }.to change(Commnent, :count).by(-1)
    end

    it "redirects to the commnents list" do
      commnent = Commnent.create! valid_attributes
      delete commnent_url(commnent)
      expect(response).to redirect_to(commnents_url)
    end
  end
end
